name: iOS CI

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode.app

      - name: Build
        run: xcodebuild clean build -project Architecture\ Homeworks.xcodeproj -scheme Architecture\ Homeworks -destination 'platform=iOS Simulator,name=iPhone 15'

      - name: Run tests
        run: xcodebuild test -project Architecture\ Homeworks.xcodeproj -scheme Architecture\ Homeworks -destination 'platform=iOS Simulator,name=iPhone 15'
